---
- name: Deploying a Red Hat High Availability cluster
  hosts: nodes
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ansible
  gather_facts: yes
  roles:
    - role: roles/redhat-ha
        
...
