---
- name: CREATE LVM FS | Ensure system_id_source is set to uname in lvm.conf
  ansible.builtin.lineinfile:
    path: /etc/lvm/lvm.conf
    regexp: '^\s*system_id_source = \"none\"'
    line: '        system_id_source = "uname"'
    backrefs: yes
    backup: yes
    state: present    

    #- debug:
    #    msg: "{{ item.ha_storage_devices }}"
    #  loop: "{{ ha_lvm_fs_list }}"
    #  run_once: true
- block:
  - name: CREATE LVM FS | Populate storage devices raw list with all devices that needs to be partioned
    set_fact:
      ha_storage_devices_raw: "{{ ha_storage_devices_raw | default([]) + item.ha_storage_devices  }}"
    loop: "{{ ha_lvm_fs_list }}"
    #run_once: true
  
    #- debug:
    #    msg: "{{ item }}"
    #  loop: "{{ ha_storage_devices_raw }}"
    #  run_once: true
  
  - name: CREATE LVM FS | Create a new primary partition
    community.general.parted:
      device: "{{ item }}"
      number: 1
      state: present
    loop: "{{ ha_storage_devices_raw }}"
    #run_once: true
  
    #- debug:
    #    msg:
    #            #- "{{ item.0.ha_instance_name }}"
    #      - "{{ item.ha_vg_name }}"
    #      - "{{ item.ha_storage_devices | product(['1']) | map('join') | list }}"
    #        #- "{{ item.0.ha_storage_devices | product(['1']) | map('join') | list }}"
    #            #- "{{ item.1.mntpoint | replace('HA_INSTANCE_NAME',item.0.ha_instance_name)}}"
    #  loop: "{{ ha_lvm_fs_list }}"
    #  run_once: true
    
  - name: CREATE LVM FS | Create a volume group on top of /dev/sda1 with physical extent size = 32MB
    community.general.lvg:
      vg: "{{ item.ha_vg_name }}"
      pvs: "{{ item.ha_storage_devices | product(['1']) | map('join') | list }}"
    loop: "{{ ha_lvm_fs_list }}"
    #run_once: true
  
    #- debug:
    #    msg:
    #      - "{{ item.0.ha_vg_name}}"
    #      - "{{ item.1.lvname}}"
    #      - "{{ item.1.lvsize }}"
    #        #- "{{ item.1.mntpoint | replace('HA_INSTANCE_NAME',item.0.ha_instance_name)}}"
    #  loop: "{{ ha_lvm_fs_list|subelements('ha_fs') }}"
    #  run_once: true
  
  - name: CREATE LVM FS | Create a logical volume of 512m
    community.general.lvol:
      vg: "{{ item.0.ha_vg_name}}" 
      lv:  "{{ item.1.lvname}}"
      size: "{{ item.1.lvsize }}"
    loop: "{{ ha_lvm_fs_list|subelements('ha_fs') }}"
    #run_once: true
  
    #- debug:
    #    msg:
    #      - "{{ item.0.ha_vg_name}}"
    #      - "{{ item.1.lvname }}"
    #      - "{{ item.1.fstype }}"
    #        #- "{{ item.1.mntpoint | replace('HA_INSTANCE_NAME',item.0.ha_instance_name)}}"
    #  loop: "{{ ha_lvm_fs_list|subelements('ha_fs') }}"
    #  run_once: true  
    
  - name: CREATE LVM FS | Create a filesystem on a lvm device
    community.general.filesystem:
      fstype: "{{ item.1.fstype }}"
      dev: "/dev/{{ item.0.ha_vg_name }}/{{ item.1.lvname }}"
    loop: "{{ ha_lvm_fs_list|subelements('ha_fs') }}"
    #run_once: true  
  run_once: true  
...
