---
# Task file that creates a fence resource using the fence_xvm fencing agent.
- debug:
    msg: "{{ item['id'] }}"

- name: STONITH | Checking if the STONITH resource exists
  ansible.builtin.command:
    cmd: "pcs stonith config {{ item['id'] }}"
  register: stonith_resource_exits
  failed_when: false
  changed_when: false

- name: STONITH | Ensuring the fence resource exists
  ansible.builtin.command:
    cmd: "pcs stonith create {{ item['id'] }} fence_xvm
            pcmk_host_list={{ item['node'] }}
            key_file={{ item['key_file'] }}
            pcmk_reboot_action=1
            op monitor interval={{ stonith_monitor_interval }}s
            meta failure-timeout={{ stonith_failure_timeout }}s migration-threshold={{ stonith_migration_threshold }}"
  register: fence_resource             
  changed_when: "'already exists' not in fence_resource['stdout']"
  when: stonith_resource_exits['rc'] != 0

- name: STONITH | Ensuring the fence resource is updated
  ansible.builtin.command:
    cmd: "pcs stonith create {{ item['id'] }} fence_xvm
            pcmk_host_list={{ item['node'] }}
            key_file={{ item['stonith_kvm_key_file'] }}
            pcmk_reboot_action=1
            op monitor interval={{ stonith_monitor_interval }}s
            meta failure-timeout={{ stonith_failure_timeout }}s migration-threshold={{ stonith_migration_threshold }}"
  when: stonith_resource_exits['rc'] == 0
...
