---
# tasks file for redhat-ha
- block:
  - name: Include Prerequisites Tasks (Optional)
    include_tasks: 00-prerequisites.yml
    args:
      apply:
        tags: prerequisites
    tags: prerequisites

  - name: Include Tasks to preparing the nodes for Red Hat High Availability cluster
    include_tasks: 01-preparing.yml
    args:
      apply:
        tags: preparing
    tags: preparing

  - name: Include Tasks to deploy the Red Hat High Availability cluster
    include_tasks: 02-deploying.yml
    run_once: true
    args:
      apply:
        tags: deploying
    tags: deploying

  - name: Include Tasks to configure stonith devices for the Red Hat High Availability cluster
    include_tasks: 03-stonith.yml
    args:
      apply:
        tags: stonith
    tags: stonith
  when: ('nodes' in group_names)

- name: Include Tasks to configure quorum
  include_tasks: 04-quorum.yml
  args:
    apply:
      tags: quorum
  tags: quorum

- name: Include Tasks to set cluster defaults global configurations
  include_tasks: 05-set_pcs_default_globals.yml
  args:
    apply:
      tags: set-pcs-default-globals
  tags: set-pcs-default-globals
  when: ('nodes' in group_names)
  run_once: true

- name: Include Tasks to configure storage layer
  include_tasks: 06-create_os_lvm_fs.yml
  args:
    apply:
      tags: create-os-lvm-fs
  tags: create-os-lvm-fs
  when: ('nodes' in group_names)

- name: Include Tasks to configure IPaddr2 resources
  include_tasks: 07-create_pcs_resources_ips.yml
  args:
    apply:
      tags: create-pcs-resources-ips
  tags: create-pcs-resources-ips
  loop: "{{ ipaddr2_list }}"
  run_once: true
  when: ('nodes' in group_names)

- name: Include Tasks to configure LVM resources
  include_tasks: 08-create_pcs_resources_lvm.yml
  args:
    apply:
      tags: create-pcs-resources-lvm
  tags: create-pcs-resources-lvm
  loop: "{{ ha_lvm_fs_list }}"
  run_once: true
  when: ('nodes' in group_names)

- name: Include Tasks to configure Filesystem resources
  include_tasks: 09-create_pcs_resources_fs.yml
  args:
    apply:
      tags: create-pcs-resources-fs
  tags: create-pcs-resources-fs
  loop: "{{ ha_lvm_fs_list|subelements('ha_fs') }}"
  run_once: true
  when: ('nodes' in group_names)
...
