---
# defaults file for redhat-ha

# Info to subscribe to RHN
#redhat_subscription_user: "{{ vault_redhat_subscription_user }}"
#redhat_subscription_password: "{{ vault_redhat_subscription_password }}"
#redhat_subscription_pool_id: "{{ vault_redhat_subscription_pool_id }}"

ha_cluster_rhsm_repos:
  - rhel-8-for-x86_64-highavailability-rpms

ha_cluster_packages:    
  - pcs
  # - fence-agents-ipmilan
  - fence-agents-all


ha_cluster_fw_ports:
   - high-availability    

ha_cluster_name: cluster-test1
ha_cluster_password: redhat00

ha_cluster_start_request_timeout: 180
ha_cluster_start_wait: 180

# STONITH
stonith_timeout: 180
stonith_monitor_interval: 200
stonith_failure_timeout: 60
stonith_migration_threshold: 5
# Fence IPMILAN
stonith_ipmi_ip: "{{ vault_ipmi_ip }}"
stonith_ipmi_login: "{{ vault_ipmi_login }}"
stonith_ipmi_password: "{{ vault_ipmi_password }}"
# Fence CISCO_UCS
stonith_cisco_ucs_ipaddr: "{{ vault_cisco_ucs_ipaddr }}"
stonith_cisco_ucs_login: "{{ vault_cisco_ucs_login }}"
stonith_cisco_ucs_passwd: "{{ vault_cisco_ucs_passwd }}"
stonith_cisco_ucs_suborg:  "{{ vault_cisco_ucs_suborg }}"
# Fence KVM
stonith_kvm_key_file_path: "/etc/cluster/fence_xvm.key"
# Quorum
ha_quorum_cluster_packages:
  - pcs
  - corosync-qnetd        
ha_quorum_dev_system_packages:
  - corosync-qdevice
ha_quorum_device_net_algorithm: ffsplit    

## Resources
ha_floating_ip_wait: 60

ha_resource_monitor_interval: 120 
ha_resource_monitor_timeout: 120 
ha_resource_start_timeout: 120 
ha_resource_stop_timeout: 120

auto_activation_local_volume_group_list:
- vg00
- vg01
- vg02
- vg03
- vg04
- vglocal  

reboot_pre_delay: 10
reboot_post_delay: 65
reboot_timeout: 1800
reboot_test_command: uptime
  
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_high_availability_clusters/assembly_controlling-cluster-behavior-configuring-and-managing-high-availability-clusters
pcs_property_list:
  - { pcs_property: symmetric-cluster, pcs_property_value: true }
  - { pcs_property: stonith-timeout, pcs_property_value: 180s }
  - { pcs_property: fence-reaction, pcs_property_value: stop }
  - { pcs_property: no-quorum-policy, pcs_property_value: stop }

# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_high_availability_clusters/assembly_configuring-cluster-resources-configuring-and-managing-high-availability-clusters#proc_configuring-resource-meta-options-configuring-cluster-resources
resource_meta_options_list:
  - { pcs_resource_meta_option: is-managed, pcs_resource_meta_option_value: true }
  - { pcs_resource_meta_option: resource-stickiness, pcs_resource_meta_option_value: 100 }
  - { pcs_resource_meta_option: failure-timeout, pcs_resource_meta_option_value: 0 }
